In [3]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). 
# You can use the reshape method -- .reshape()

import numpy as np

# Create a 1D array with 12 elements        
arr = np.arange(12)
# Reshape the 1D array into a 3D array with shape (2, 3, 2)
reShapedArray = arr.reshape((2, 3, 2))  
# Print the resulting 3D array
print(reShapedArray) 

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
array_linspace = np.linspace(0, 20, 6)
    
print(array_linspace)


[ 0.  4.  8. 12. 16. 20.]


In [5]:
# 9. Make a Deep Copy of the above array
import numpy as np

# Original array
arr = np.linspace(0, 20, 6)

# Deep copy
deep_copy = np.copy(arr)

print("Original:", arr)
print("Deep Copy:", deep_copy)


Original: [ 0.  4.  8. 12. 16. 20.]
Deep Copy: [ 0.  4.  8. 12. 16. 20.]


In [6]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...
# ([[25, 16]])
#        ([[11, 2], [13, 4]])
#       ([[7, 81], [5, 6], [11, 12]])

import numpy as np

a = np.array([[25, 16]])
b = np.array([[11, 2], [13, 4]])
c = np.array([[7, 81], [5, 6], [11, 12]])

# Concatenate along rows (axis=0)
newArray = np.concatenate((a, b, c), axis=0)

print("newArray:\n", newArray)


newArray:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [7]:
# 11. Sort 'newArray' in order into 'sortedArray'
# Sort each row individually
sortedArray = np.sort(newArray, axis=1)
print("Each row sorted:\n", sortedArray)

Each row sorted:
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [8]:
# 12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
#reshaped_arr = reShapedArray.reshape(2, 3, 2)

print('ReShaped Array',reShapedArray)

# Unpack the first four 2-element arrays from reShapedArray
first_pair = reShapedArray[0, 0]
second_pair = reShapedArray[0, 1]
third_pair = reShapedArray[0, 2]
fourth_pair = reShapedArray[1, 0]
print('------------------------')
print("First pair:", first_pair)
print("Second pair:", second_pair)
print("Third pair:", third_pair)
print("Third pair:", fourth_pair)


ReShaped Array [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
------------------------
First pair: [0 1]
Second pair: [2 3]
Third pair: [4 5]
Third pair: [6 7]


In [9]:
#13. Combined and sort the following arrays into one called 'comboArray' ...
#one = ([10, 11, 12, 13, 14, 15, 16, 17])
#two = ([20, 21, 22, 23, 24, 25, 26, 27])
#three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])
# Combine the arrays
comboArray = np.concatenate((one, two, three))
# Sort the combined array
comboArray = np.sort(comboArray)
print("Combined and sorted array:", comboArray)


Combined and sorted array: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [19]:
# 14. Take 'comboArray' and perform the following slicing activities:

# print sec1 - the 2nd element

# print sec2 - all elements from the 3rd element to the last

# print sec3 - all elements from the 4th to the 14th elements

# print sec4 - the last 6 elements

# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. 
# taking a section from the end.

# print sec6 - from #20 every even element to the end

# print sec7 - from the last element moving forward, every 5th element.

sec1 = comboArray[1]
print("sec1:", sec1)

sec2 = comboArray[2:]
print("sec2:", sec2)

sec3 = comboArray[3:14]
print("sec3:", sec3)

sec4 = comboArray[-6:]
print("sec4:", sec4)

sec5 = comboArray[:-10]
print("sec5:", sec5)

numbers_from_20 = comboArray[16:]
print("Numbers from 20:", numbers_from_20)
sec6 = numbers_from_20[numbers_from_20 % 2 == 0]
print("sec6:", sec6)  

sec7 = comboArray[-1::-5]
print("sec7:", sec7)


sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
Numbers from 20: [20 21 22 23 24 25 26 27]
sec6: [20 22 24 26]
sec7: [27 22 15 10  3]


In [11]:
# Using Series, create a DataFrame that looks like this:

# IngredientsQuantityUnitFlour4cupsMilk1cupEggs2largeSpam1can

# Name: Dinner, dtype: object

import pandas as pd

# Create a dictionary with the data
data = {
    'Flour': ['4', 'cups'],
    'Milk': ['1', 'cup'],
    'Eggs': ['2', 'large'],
    'Spam': ['1', 'can']
}

# Convert the dictionary to a Series of strings
dinner_series = pd.Series(
    [f"{qty} {unit}" for qty, unit in data.values()],
    index=data.keys(),
    name="Dinner"
)

print(dinner_series)


Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object


In [12]:
# 16. Take this data and create a DataFrame named studentData

#    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#         'Height': [5.1, 6.2, 5.1, 5.2],
#         'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#         'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#         'Age': [21, 23, 24, 21],
#         'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#         'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
#     }

import pandas as pd

# Given data
data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

# Create DataFrame
studentData = pd.DataFrame(data)

# Display the DataFrame
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [13]:
# 17. Add a new column to the DataFrame with the following deserts: 
# ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['Desserts'] = desserts
print("Updated DataFrame with Desserts:\n", studentData)

Updated DataFrame with Desserts:
       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [14]:
# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData_sorted = studentData.sort_values(by=['Name', 'address'], ascending=True)
print("Sorted DataFrame:\n", studentData_sorted)    


Sorted DataFrame:
       Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [15]:
# 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
#  df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

import pandas as pd

# Create the DataFrame
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

# Save to CSV file
df.to_csv('cows_and_goats.csv')

print("DataFrame saved as 'cows_and_goats.csv'")


DataFrame saved as 'cows_and_goats.csv'


In [16]:
import pandas as pd

# Create a DataFrame about vegetables
veg_data = {
    'Vegetable': ['Carrot', 'Broccoli', 'Spinach', 'Peas'],
    'Quantity': [10, 5, 8, 12],
    'Unit': ['kg', 'kg', 'kg', 'kg'],
    'Price_per_kg': [2.5, 3.0, 4.0, 2.0]
}

veg_df = pd.DataFrame(veg_data)

# Save to CSV
veg_df.to_csv('vegetables.csv', index=False)

print("vegetables.csv saved!")

# Making changes to vegetables.csv

# Load the CSV file
veg_df_loaded = pd.read_csv('vegetables.csv')

# Let's say we update the quantity of 'Carrot' and add a new vegetable
veg_df_loaded.loc[veg_df_loaded['Vegetable'] == 'Spinach', 'Quantity'] = 15

# Add a new row
# Create new row as a DataFrame
new_veg = pd.DataFrame([{
    'Vegetable': 'Tomato',
    'Quantity': 20,
    'Unit': 'kg',
    'Price_per_kg': 1.8
}])

veg_df_updated = pd.concat([veg_df_loaded, new_veg], ignore_index=True)

# Save the updated DataFrame as a new CSV
veg_df_updated.to_csv('vegetables_updated.csv', index=False)

print("vegetables_updated.csv saved with changes!")



vegetables.csv saved!
vegetables_updated.csv saved with changes!


# 1. What does Pandas stand for?
**"Pan"**el **"Da"**ta → Pandas

It was created to make data analysis in Python easier, especially for structured data (like spreadsheets or SQL tables).



# 2. What are the 2 collections used in Pandas?
Series, DataFrame

# 3. Name 4 things Pandas can do for us.
Data Cleaning
Data Analysis and Aggregation
Data Filtering and Selection
Read/Write Data of various formats CSV, Excel, JSON, SQL


# 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
inplace = True

# 5. What is a CSV?
CSV stands for Comma-Separated Values.It’s a plain text file format used to store tabular data (like rows and columns) where:

Each row is a line in the file.

Each value (or column) in a row is separated by a comma.

# 6. When cleaning data what values do we not like in our data?
Missing values, Duplicate Rows, Inconsistent formatting, Invalid values, Wrong datatypes.